// Sites-only map format <-> full voronoi geometry.
//
// A map is fully determined by its voronoi sites + the bounding box they were
// computed in. The editor authors a map by running voronoi.compute(sites, bbox)
// and the OLD on-disk format stored that entire returned diagram (cells, edges,
// vertices, plus a per-halfedge copy of every shared edge) — ~1.3 MB per map.
//
// The compact format stores only what can't be regenerated:
//   { bbox:{xl,xr,yt,yb}, sites:[{x,y,id}], hazards, startEdges, name, author, id }
// and we recompute the diagram on load. Reconstruction is deterministic: same
// site coordinates + same bbox => identical cells/edges/voronoiId assignment, so
// adjacency (cellGraph), par-time, AI pathing, collision and rendering all see
// exactly the geometry the editor produced. The migration's equivalence test
// proves this per map before any original is replaced.
//
// rhill assigns voronoiId in the order sites are *processed* (sorted), not input
// order, and mutates each passed site object with its assigned voronoiId. So we
// reconstruct by tracking each site object through compute() and reading back the
// voronoiId it received — never by assuming input order equals voronoiId.

var Voronoi = require('../client/scripts/rhill-voronoi-core.js');

// "Sites-only" = has a sites array and NO full geometry. The `!cells` check keeps
// this identical to the client's mapIsSitesOnly: a map carrying both must be
// treated as full-geometry on both sides, never reconstructed on one and passed
// through on the other.
function isSitesOnly(map) {
    return map != null && Array.isArray(map.sites) && !Array.isArray(map.cells);
}

// The bbox is recoverable from a full map's clipped polygon vertices: voronoi
// clipping snaps boundary cells' edges exactly onto the bbox lines, so the
// min/max of every halfedge endpoint (va/vb) is the bbox. (The diagram's own
// `vertices` array is NOT usable here — it retains un-clipped circle-event points
// that lie far outside the box.)
//
// CRITICAL: the clip-intersection math leaves ~1e-13 float dust on those min/max
// values (e.g. 74.99999999999999 instead of 75). The editor always computes with a
// clean bbox (integer world dims + integer gate depth), so we round the recovered
// value back to that clean grid. Without this, reconstruct() runs voronoi.compute
// with a *slightly* different bbox than the original, producing geometry that
// differs by ~1e-13 — invisible to the eye, but enough to flip a borderline
// AI-pathing assertion (the start-edges test). Rounding makes reconstruction
// BIT-IDENTICAL to the original geometry (verified diff == 0 across all maps).
function snap(v) { return Math.round(v * 1e6) / 1e6; }
function deriveBbox(fullMap) {
    var xl = Infinity, xr = -Infinity, yt = Infinity, yb = -Infinity;
    var cells = fullMap.cells;
    for (var i = 0; i < cells.length; i++) {
        var hes = cells[i].halfedges;
        for (var h = 0; h < hes.length; h++) {
            var edge = hes[h].edge;
            if (!edge) { continue; }
            var pts = [edge.va, edge.vb];
            for (var p = 0; p < pts.length; p++) {
                var v = pts[p];
                if (!v) { continue; }
                if (v.x < xl) { xl = v.x; }
                if (v.x > xr) { xr = v.x; }
                if (v.y < yt) { yt = v.y; }
                if (v.y > yb) { yb = v.y; }
            }
        }
    }
    return { xl: snap(xl), xr: snap(xr), yt: snap(yt), yb: snap(yb) };
}

// Geometry/derived fields are regenerated by reconstruct() (or ARE the sites-only
// representation), so they must not be carried. EVERYTHING else must survive the
// round trip — carry by DENYLIST, not an allowlist: the lobby map ships
// `spawnPad`/`stations`, and future map types may add their own fields; an allowlist
// silently drops them (it dropped the lobby stations, which broke lobby bot
// behavior). thumbnail is the one intentional drop (regenerated on demand). Existing
// dst keys (e.g. the hazards normalized by the caller) are left untouched.
var GEOMETRY_KEYS = { cells: true, edges: true, vertices: true, execTime: true, thumbnail: true, sites: true, bbox: true };
function carryMeta(dst, src) {
    for (var k in src) {
        if (GEOMETRY_KEYS[k]) { continue; }
        if (dst[k] === undefined) { dst[k] = src[k]; }
    }
    return dst;
}

// Full geometry -> compact sites-only. Used by the migration and at the submit
// boundary so the editor's full in-memory diagram is reduced to one canonical
// stored shape.
function toSitesOnly(fullMap) {
    var sites = new Array(fullMap.cells.length);
    for (var i = 0; i < fullMap.cells.length; i++) {
        var c = fullMap.cells[i];
        sites[i] = { x: c.site.x, y: c.site.y, id: c.id };
    }
    var out = { bbox: deriveBbox(fullMap), sites: sites, hazards: fullMap.hazards || [] };
    return carryMeta(out, fullMap);
}

// Compact sites-only -> full geometry, by recomputing the voronoi diagram. The
// returned object is structurally identical to an old-format loaded map (cells
// with site/halfedges/edge/va/vb, plus the carried metadata), so every consumer
// is unchanged. Throws on a degenerate site set (a duplicate site produces no
// cell), which the migration treats as "keep this map in full format".
// Runtime cap on cells/sites — mirrored from .github/scripts/validate-submitted-map.js
// (the offline PR validator), where it's documented as "largest committed map is
// 470; this is generous headroom". Enforced here so a crafted preview/submit can
// never reach voronoi.compute on the shared server process with a giant payload.
var MAX_MAP_CELLS = 2500;

function reconstruct(sitesMap) {
    if (sitesMap.bbox == null || !Array.isArray(sitesMap.sites)) {
        throw new Error('reconstruct: map is missing bbox or sites');
    }
    if (sitesMap.sites.length > MAX_MAP_CELLS) {
        throw new Error('reconstruct: too many sites (' + sitesMap.sites.length + ' > ' + MAX_MAP_CELLS + ')');
    }
    // Voronoi compute is undefined on non-finite or inverted bboxes — guard so
    // a crafted bbox can't produce garbage cells or hang the algorithm.
    var bb = sitesMap.bbox;
    if (!Number.isFinite(bb.xl) || !Number.isFinite(bb.xr) ||
        !Number.isFinite(bb.yt) || !Number.isFinite(bb.yb) ||
        bb.xr <= bb.xl || bb.yb <= bb.yt) {
        throw new Error('reconstruct: invalid bbox');
    }
    var siteObjs = new Array(sitesMap.sites.length);
    for (var i = 0; i < sitesMap.sites.length; i++) {
        var s = sitesMap.sites[i];
        if (s == null || !Number.isFinite(s.x) || !Number.isFinite(s.y)) {
            throw new Error('reconstruct: site ' + i + ' has non-finite coordinates');
        }
        siteObjs[i] = { x: s.x, y: s.y };
    }
    var diagram = new Voronoi().compute(siteObjs, sitesMap.bbox);
    // rhill's Diagram constructor leaves a vestigial top-level `site` (null, never
    // populated or read); drop it so the reconstructed map is clean.
    delete diagram.site;
    for (var j = 0; j < sitesMap.sites.length; j++) {
        var vid = siteObjs[j].voronoiId;
        if (vid == null || diagram.cells[vid] == null) {
            throw new Error('reconstruct: site ' + j + ' (' + sitesMap.sites[j].x + ',' +
                sitesMap.sites[j].y + ') produced no cell — duplicate or degenerate site');
        }
        diagram.cells[vid].id = sitesMap.sites[j].id;
    }
    diagram.hazards = sitesMap.hazards || [];
    return carryMeta(diagram, sitesMap);
}

// Convenience for code that reads a map file and needs full geometry regardless
// of which format it's in: reconstruct a sites-only map, pass a full map through.
function hydrate(map) {
    return isSitesOnly(map) ? reconstruct(map) : map;
}

module.exports = { isSitesOnly: isSitesOnly, reconstruct: reconstruct, toSitesOnly: toSitesOnly, deriveBbox: deriveBbox, hydrate: hydrate, MAX_MAP_CELLS: MAX_MAP_CELLS };
